### ISSUE TITLE
Short_URL's for Wikihousing?

### ISSUE THREAD

**Issue by theryankelly** [codeisland/healthy-homes#10]
Do we want shot urls: http://www.mediawiki.org/wiki/Manual:Short_URL?

http://wikihousing.org/Lead
instead of
http://wikihousing.org/mediawiki/index.php/Lead

**Comment by goldenmeanie** [comment]
I think that would be much nicer. I don't fully understand why those don't work now. I checked this morning to see if we could just truncate them. I assume there is some server funny business going on to replace the home page with the search page.

**Comment by tomlancaster** [comment]
Yes, it's a server config issue. Happy to take a look if someone can provide access.

**Comment by goldenmeanie** [comment]
<VirtualHost *:80>
	ServerName www.wikihousing.org
	ServerAlias wikihousing.org

	ServerAdmin webmaster@localhost

	DocumentRoot /var/www/healthy-homes/

        Alias /mediawiki /var/www/mediawiki

	LogLevel warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
        <Directory /var/www/healthy-homes/>
            Options Indexes FollowSymLinks MultiViews
            AllowOverride All
            Order allow,deny
            allow from all
        </Directory>
    </VirtualHost>

@tomlancaster

**Comment by tomlancaster** [comment]
@goldenmeanie what's in the .htaccess under /var/www/healthy-homes ?

**Comment by goldenmeanie** [comment]
There isn't one.

**Comment by tomlancaster** [comment]
```
<VirtualHost *:80>
ServerName www.wikihousing.org
ServerAlias wikihousing.org

ServerAdmin webmaster@localhost

DocumentRoot /var/www/healthy-homes/

    Alias /w /var/www/mediawiki

LogLevel warn

ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
    <Directory /var/www/healthy-homes/>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
        RewriteEngine on
        RewriteRule ^/?wiki(/.*)?$ /w/index.php [PT,L]

        RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} !-f
        RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} !-d
        RewriteRule ^(.*)$ /w/index.php [PT,L]
    </Directory>
</VirtualHost>
```
something like this should work, but according to the docs you'll also need to edit the mediawiki LocalSettings.php as follows:
```
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/w";
$wgArticlePath = "/wiki/$1";
```
This will give article URLs like /wiki/Foo_and_Bar, and remove the ugly index.php from the path.

**Comment by goldenmeanie** [comment]
Is the "wiki" level non-negotiable?

**Comment by tomlancaster** [comment]
@goldenmeanie I think because you're hosting something in a non-wikimedia directory (/var/www/healthy-homes/) you need something to distinguish what should be served by the wiki engine. It doesn't have to be "wiki" however.

**Comment by goldenmeanie** [comment]
Thanks @tomlancaster I've implemented your code. I really appreciate the help!

**Comment by tomlancaster** [comment]
@goldenmeanie it worked as-is? Slightly surprised since it was untested.

On Mon, Mar 9, 2015 at 11:02 PM, Alex Taylor <notifications@github.com>
wrote:

> Thanks @tomlancaster <https://github.com/tomlancaster> I've implemented
> your code. I really appreciate the help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeisland/healthy-homes/issues/10#issuecomment-77987834>
> .
>



-- 
-------
Vice President, Engineering
InCrowd, Inc.

**Comment by goldenmeanie** [comment]
I haven't found a problem with it yet. I did have to adjust some links in the splash page and, as you suggested edit the LocalSettings.php file. But it seems to be working fine. Thanks again!
