### ISSUE TITLE
First two SVG icons are broken in Safari

### ISSUE THREAD

**Issue by goldenmeanie** [codeisland/healthy-homes#12]

**Comment by goldenmeanie** [comment]
First two SVG icons are actually bitmaps. @theryankelly who acquired the icons from noun project? We could try to:

1. re-download
2. just redraw.

**Comment by andrewborstein** [comment]
I think I made the original SVGs from PNG's that someone at Code
Island made. I just took them off of github and probably used some online
converter to create them. I remember having some issues the first time, but
I thought I had worked around them. The original files are definitely in
a long github thread, somewhere in this repo.


On Monday, May 18, 2015, Alex Taylor <notifications@github.com> wrote:

> First two SVG icons are actually bitmaps. @theryankelly
> <https://github.com/theryankelly> who acquired the icons from noun
> project? We could try to:
>
>    1. re-download
>    2. just redraw.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeisland/healthy-homes/issues/12#issuecomment-103260554>
> .
>


-- 

---

*Andrew Borstein *| Full Stack Developer
andrewborstein.com | linkedin <http://linkedin.com/in/andrewborstein> |
github <http://github.com/andrewborstein> | 401.996.1212

**Comment by goldenmeanie** [comment]
Thanks @andrewborstein, I'll look for those later today.

**Comment by goldenmeanie** [comment]
Got them, and redrew one and it fixes the issue. Will do the other one later.

**Comment by goldenmeanie** [comment]
Fixed!
