### ISSUE TITLE
Add Mass Delete Function

### ISSUE THREAD

**Issue by theryankelly** [codeisland/healthy-homes#13]
We need to add a mass delete function to the site to help remove the spam that was created before we locked the site. 

This might work well
http://www.mediawiki.org/wiki/Extension:Nuke

**Comment by goldenmeanie** [comment]
I've installed BlockAndNuke. It needs a whitelist of users to preserve (and their content). @jwortzel can you provide that list?

**Comment by theryankelly** [comment]
manual mass delete was a success! Thanks @goldenmeanie
