### ISSUE TITLE
Tell Jonathan and Jeremy the credentials to get into the wikihousing server

### ISSUE THREAD

**Issue by jonathanglister** [codeisland/healthy-homes#15]
Jeremy and I do not know the password to get into the Wikihousing website server (we have the DigitalOcean credentials but cannot login at the VNC terminal screen.) Would someone mind shooting me (jonathan_lister@brown.edu) or Jeremy (jeremy_wortzel@brown.edu) an email with the username and password?

**Comment by goldenmeanie** [comment]
@jonathanglister @jwortzel please join the slack and we can get that sorted out. Email is not a secure way to share login credentials!

**Comment by jrumbut** [comment]
Speaking of slack, I've been hoping to get more involved but the meeting time doesn't work for me. Are there other communication channels in use?

**Comment by theryankelly** [comment]
@jrumbut We have focused on using Slack as our main communication tool and GitHub as home for projects.  But we can always be reach through social media ([twitter](https://twitter.com/code_island), [facebook](https://www.facebook.com/codeislandbrigade/), [meetup](http://www.meetup.com/Rhode-Island-Code-for-America-Brigade/), [g+](https://plus.google.com/u/0/communities/112228497378493874687) or [email](info@code-island.org)).  We are looking into new meeting times for next year and are always looking for support pumping out social media content and creating clear GitHub issues for project tasks.
