### ISSUE TITLE
Account editing options for Media Wiki

### ISSUE THREAD

**Issue by theryankelly** [codeisland/healthy-homes#2]
What are the Media wiki options for account creation in media wiki? Open for anyone to create an account by default?  Is there an option for Admin approval of accounts? How/ where is this setting changed?

**Comment by theryankelly** [comment]
Thanks @FreedomFighterSparrow.  We were able to install the Confirm Account Extension.  We just need to set the correct admin email address to call this complete.

**Comment by theryankelly** [comment]
Email problem: http://www.mediawiki.org/wiki/Manual:$wgSMTP

**Comment by theryankelly** [comment]
Email setting problem on gmail side has been resolved.

@jwortzel if you could test the process of creating and confirming a new account, I think we can close this issue out.

**Comment by jwortzel** [comment]
@theryankelly I've just attempted to create a new account on wikihousing and it seems that I was able to send in the request form, confirm my email address, but I have not seen an email arrive at wikihousing@gmail.com for me to approve the account creation. I'm not sure how long the email takes to be sent, but if it's more than 15 minutes, there may be a slight glitch.

**Comment by jwortzel** [comment]
Hey @theryankelly. I hope all is well, I just wanted to check in to see if this issue has been resolved? Wikihousing@gmail.com still hasn't received and email to approve the pseudo account that I have tried to establish. Let me know if I can help in anyway. Thanks!

**Comment by theryankelly** [comment]
Confirmation email is sent to new user (screenshot) but application is not being received by admin
![Uploading Screen Shot 2015-03-16 at 8.44.48 PM.png . . .]()

**Comment by theryankelly** [comment]
@jwortzel We have been able to resolve this issue! Thanks to @joealba.  To confirm request accounts navigate as admin to  http://wikihousing.org/wiki/Special:ConfirmAccounts.  We have also updated media wiki and extensions as of 7/6/2015 The confirm account extension does have a file path problem issue that is

**Comment by theryankelly** [comment]
@jwortzel We have been able to resolve this issue! Thanks to @joealba.  To confirm request accounts navigate as admin to  http://wikihousing.org/wiki/Special:ConfirmAccounts.
