### ISSUE TITLE
Add relative urls for splash links

### ISSUE THREAD

**Issue by theryankelly** [codeisland/healthy-homes#6]
Our four image links are

/Housing_Hazards
/Housing_Policies
/Housing_Resources
/Structural_Systems

Top Links

/About_wikihousing
/Get_Involved
RIAHH (for near future): https://twitter.com/RIHealthyHomes

**Comment by andrewborstein** [comment]
All set.

**Comment by andrewborstein** [comment]
These relative links aren't working on the [current page](http://104.131.241.94/healthy-homes/). 

For example, the 'About' link points to [http://104.131.241.94/About_wikihousing](http://104.131.241.94/About_wikihousing) while it should be [http://104.131.241.94/mediawiki/index.php/About_wikihousing](http://104.131.241.94/mediawiki/index.php/About_wikihousing). So each link needs to begin with  __/mediawiki/index.php__.

**Comment by goldenmeanie** [comment]
We'll want to switch these back once we close [#9](https://github.com/codeisland/healthy-homes/issues/9)
