### ISSUE TITLE
Point wikihousing.org at the site

### ISSUE THREAD

**Issue by goldenmeanie** [codeisland/healthy-homes#9]

**Comment by theryankelly** [comment]
WIKIHEALTHYHOMES.COM
WIKIHEALTHYHOMES.INFO
WIKIHEALTHYHOMES.NET
WIKIHEALTHYHOMES.ORG
WIKIHEALTHYHOUSING.COM
WIKIHEALTHYHOUSING.INFO
WIKIHEALTHYHOUSING.NET
WIKIHEALTHYHOUSING.ORG
WIKIHOUSING.NET
WIKIHOUSING.ORG

All now point to the media wiki site
